snmp:
  - name: primary-snmp
    bind-addr: ":1161"
    community-ro: public
    oids:
      - ".1.3.6.1.2.1.1.1.0/4/string/Some version of mockdev - primary"
      - ".1.3.6.1.2.1.1.4.0/4/string/https://github.com/thorsager/mockdev"
      - ".1.3.6.1.2.1.1.5.0/4/string/mockdev.local"
      - ".1.3.6.1.2.1.1.6.0/4/string/The World"
  - name: secondary-snmp
    bind-addr: ":1162"
    community-ro: public
    oids:
      - ".1.3.6.1.2.1.1.1.0/4/string/Some version of mockdev - secondary"
      - ".1.3.6.1.2.1.1.4.0/4/string/https://github.com/thorsager/mockdev"
      - ".1.3.6.1.2.1.1.5.0/4/string/mockdev.local"
      - ".1.3.6.1.2.1.1.6.0/4/string/The World"
