#snmp:
#  - name: default
#    # bind addr and port
#    bind-addr: ":1161"
#    # read only community
#    community-ro: public
#    # specify a list of 'snmp-snapshot' files, they will be read in order and
#    # later additions of a existing oid will override any previously defined.
#    snapshot-files:
#      - gw-snapshot.txt
#    # specific oids put here will override what is read from snap-shot files
#    oids:
#      - .1.3.6.1.2.1.1.1.0/4/string/FakeIt v.1

http:
  - name: default
    bind-addr: ":8080"
    # specify a list of 'conversation' files, these are basically files,
    # containing conversation objects, as the one shown below.
    conversation-files:
      - http_conversations/simple.yaml
      - http_conversations/file.yaml
    conversations:
      - name: "hello world"
        request:
          url-matcher:
            path: /hello
          method-matcher: .*
          header-matchers:
          body-matcher: .*
        response:
          status-code: 200
          headers:
            - "Content-Type: text/plain"
          body: Hello World, from mocdevd

#ssh:
#  - name: default
#    bind-addr: ":2222"
#    host-keys:
#    default-prompt: "> "
#    default-response: "command not found."
#    eol: "\r\n"
#    users:
#      - name: joe
#        password: "dalton"
#      - name: averal
#        public-key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMtdlldg8rw54JMzLCRwrQ4o2vTn6MhxVqdne87/Dpn+eBnF7cSRQGgHHcSG6l4JH1QmOxV0rqNc3msH37VIcy8= mit@Michaels-MacBook-Pro.local
#    conversations:
#      request: "ls -1"
#      response: |
#        .
#        ..
#        first_filename.txt
#        another-file.txt
#      prompt-prefix: "foo"